/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.62).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

package es.unex.swagger.api;


import es.unex.swagger.model.PerfilUsuario;
import es.unex.swagger.model.User;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2024-10-18T10:29:32.211856553Z[GMT]")
@Validated
public interface ProfilesApi {

    @Operation(summary = "Elimina la información sobre un perfil dado su id.", description = "Elimina toda la información un perfil de un usuario dado el id del usuario y el id del perfil", security = {
        @SecurityRequirement(name = "cookieAuth"),
@SecurityRequirement(name = "medifli_auth", scopes = {
            "write:users",
"read:users"        })    }, tags={ "user-profile" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Operación exitosa."),
        
        @ApiResponse(responseCode = "400", description = "Valor no soportado"),
        
        @ApiResponse(responseCode = "404", description = "Usuario o perfil de usuario no encontrado") })
    @RequestMapping(value = "/profiles/{idProfile}",
        method = RequestMethod.DELETE)
    ResponseEntity<PerfilUsuario> deleteUserProfileById(@Parameter(in = ParameterIn.PATH, description = "El id del perfil de usuario que se desea eliminar.", required=true, schema=@Schema()) @PathVariable("idProfile") Long idProfile
, @Parameter(in = ParameterIn.COOKIE, description = "" ,required=true,schema=@Schema()) @CookieValue(value="SessionUserCookie", required=true) User sessionUserCookie
);


    @Operation(summary = "Devuelve todos los perfiles del usuario dada su id.", description = "Devuelve todos los perfiles del usuario.", security = {
        @SecurityRequirement(name = "cookieAuth"),
@SecurityRequirement(name = "medifli_auth", scopes = {
            "write:users",
"read:users"        })    }, tags={ "user-profile" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Operación exitosa.", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = PerfilUsuario.class)))),
        
        @ApiResponse(responseCode = "400", description = "Valor no soportado"),
        
        @ApiResponse(responseCode = "404", description = "Perfil no encontrado") })
    @RequestMapping(value = "/profiles",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<PerfilUsuario>> getAllUserProfileById(@Parameter(in = ParameterIn.COOKIE, description = "" ,required=true,schema=@Schema()) @CookieValue(value="SessionUserCookie", required=true) User sessionUserCookie
);


    @Operation(summary = "Devuelve la información sobre un perfil dado su id.", description = "Devuelve la información sobre un perfil de un usuario dado el ide del usuario y el id del perfil", tags={ "user-profile" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Operación exitosa.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = PerfilUsuario.class))),
        
        @ApiResponse(responseCode = "400", description = "Valor no soportado"),
        
        @ApiResponse(responseCode = "404", description = "Perfil no encontrado") })
    @RequestMapping(value = "/profiles/{idProfile}",
        produces = { "application/json", "application/xml", "application/x-www-form-urlencoded" }, 
        method = RequestMethod.GET)
    ResponseEntity<PerfilUsuario> getUserProfileById(@Parameter(in = ParameterIn.PATH, description = "El id del perfil de usuario que se desea buscar.", required=true, schema=@Schema()) @PathVariable("idProfile") Long idProfile
, @Parameter(in = ParameterIn.COOKIE, description = "" ,required=true,schema=@Schema()) @CookieValue(value="SessionUserCookie", required=true) User sessionUserCookie
);


    @Operation(summary = "Añade un nuevo perfil de usuario", description = "Añade un nuevo perfil a un usuario, facilitando la información en el body de la petición.", security = {
        @SecurityRequirement(name = "cookieAuth"),
@SecurityRequirement(name = "medifli_auth", scopes = {
            "write:users",
"read:users"        })    }, tags={ "user-profile" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Operación exitosa.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = PerfilUsuario.class))),
        
        @ApiResponse(responseCode = "400", description = "Valor no soportado"),
        
        @ApiResponse(responseCode = "404", description = "Perfil no encontrado") })
    @RequestMapping(value = "/profiles",
        produces = { "application/json", "application/xml", "application/x-www-form-urlencoded" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<PerfilUsuario> postUserProfile(@Parameter(in = ParameterIn.DEFAULT, description = "", schema=@Schema()) @Valid @RequestBody PerfilUsuario body
);


    @Operation(summary = " Actualiza la información sobre un perfil dado su id.", description = "Actualiza toda la información un perfil de un usuario dado su id", security = {
        @SecurityRequirement(name = "cookieAuth"),
@SecurityRequirement(name = "medifli_auth", scopes = {
            "write:users",
"read:users"        })    }, tags={ "user-profile" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Operación exitosa.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = PerfilUsuario.class))),
        
        @ApiResponse(responseCode = "400", description = "Valor no soportado"),
        
        @ApiResponse(responseCode = "404", description = "Perfil no encontrado") })
    @RequestMapping(value = "/profiles/{idProfile}",
        produces = { "application/json", "application/xml", "application/x-www-form-urlencoded" }, 
        consumes = { "application/json", "application/xml", "application/x-www-form-urlencoded" }, 
        method = RequestMethod.PUT)
    ResponseEntity<PerfilUsuario> putUserProfileById(@Parameter(in = ParameterIn.PATH, description = "El id del perfil de usuario que se desea eliminar.", required=true, schema=@Schema()) @PathVariable("idProfile") Long idProfile
, @Parameter(in = ParameterIn.COOKIE, description = "" ,required=true,schema=@Schema()) @CookieValue(value="SessionUserCookie", required=true) User sessionUserCookie
, @Parameter(in = ParameterIn.DEFAULT, description = "", schema=@Schema()) @Valid @RequestBody PerfilUsuario body
);

}

